### ISSUE TITLE
[Bug]: File suffix other than .ini gives warnings

### ISSUE THREAD

**Issue by TBarregren** [DevelopersToolbox/ini-file-parser#3]
### What happened?

I am executing the following:

```bash
cat <<EOT > test.ini
[my_test]
test_1 = A
EOT

cp test.ini test.conf

source ini-file-parser.sh

echo "test.ini"
process_ini_file test.ini

echo "test.conf"
process_ini_file test.conf
```

The resulting output:

```bash
test.ini
test.conf
[ WARNING ] key test_1 - Defined multiple times within section my_test
```

### Expected behavior

The expected output:

```bash
test.ini
test.conf
```

### How do we reproduct the bug?

1. Open an terminal.
2. Change the terminal's working directory to `…/ini-file-parser/src`.
3. Copy the above script and paste it into the terminal.

### Relevant log output

```shell
[ WARNING ] key test_1 - Defined multiple times within section my_test
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TBarregren** [comment]
Thanks for the quick response (and great script). I realize my mistake. i got the "error" when i tested the script. In reality, it won't be a problem. So for me it only remains to suggest to mention this to the documenation. Hats off.

**Comment by TGWolf** [comment]
I will add it to my backlog, as I like the idea of being able to purge loaded items or remove specific items and maybe even add a function to write the merged config into a new file.

To be honest this only exists because of a bet. A friend said he had never seen an ini file parser for bash (most languages have one or several implementations). I said it shouldn't be that hard to do it, and his reply was "I bet you can't" ... so I did :)

I have a lot of other projects on the go, and never really came back to this one to see what new cool things I could add to it, so it is nice to get a reminder it is still out there.
